const ALARM_TYPES = {
  HARD_IMPACT: 'HARD_IMPACT',
  FALL_RISK: 'FALL_RISK',
  INACTIVITY: 'INACTIVITY',
  LOW_BATTERY: 'LOW_BATTERY',
  CONNECTION_LOST: 'CONNECTION_LOST',
  EMERGENCY_BUTTON: 'EMERGENCY_BUTTON',
  DANGER_ZONE_ENTRY: 'DANGER_ZONE_ENTRY'
};

const ALARM_TYPE_VALUES = Object.values(ALARM_TYPES);

module.exports = {
  ALARM_TYPES,
  ALARM_TYPE_VALUES
};
